---
- name: dummy
  hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
  - name: install basic packages
    yum: name="{{ item }}" state=present
    with_items:
      - unzip