---
- name: my playbook test
  hosts: all
  remote_user: "{{ remote_user | default(root) }}"
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
  - name: install basic packages
    yum: name="{{ item }}" state=present
    with_items:
      - unzip

  roles:  
    - { role: geerlingguy.java }